name: traka
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.5+6

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.0
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.2.0
  firebase_storage: ^12.3.4
  firebase_crashlytics: ^4.1.3
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_text_recognition: ^0.15.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  local_auth: ^2.3.0
  device_info_plus: ^11.2.0
  uuid: ^4.5.1
  face_verification: ^0.3.3
  path_provider: ^2.1.5
  path: ^1.9.0
  image: ^4.3.0
  camera: ^0.11.0+2
  http: ^1.2.0
  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.3.1
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  record: ^6.2.0
  just_audio: ^0.9.40
  video_player: ^2.9.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  in_app_purchase: ^3.2.0
  share_plus: ^12.0.1
  flutter_contacts: ^1.1.9+2
  package_info_plus: ^9.0.0
  in_app_update: ^4.2.5
  shimmer: ^3.0.0
  flutter_webrtc: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

# Konfigurasi icon aplikasi
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_traka.png"
  min_sdk_android: 21

# Native splash â€” tampil segera saat app dibuka (sebelum Flutter siap)
flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo_traka.png"
  android_12:
    color: "#000000"
    image: "assets/images/logo_traka.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
